import argparse
from pathlib import Path

from convert_bmps_to_rgb565 import DEFAULT_GAMMA, build_color_lut, decode_bmp_to_rgb565


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
DEFAULT_SOURCE_DIR = PROJECT_ROOT / "sprites"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "bin" / "sprites"
DEFAULT_MANIFEST_NAME = "sprite_manifest.py"


def parse_rgb_triplet(value):
    if value is None:
        return None

    parts = [part.strip() for part in str(value).split(",")]
    if len(parts) != 3:
        raise ValueError("transparent key must be in r,g,b format")

    triplet = tuple(int(part) for part in parts)
    if any(component < 0 or component > 255 for component in triplet):
        raise ValueError("transparent key components must be between 0 and 255")
    return triplet


def write_manifest(path, records, transparent_key):
    lines = [
        "# Auto-generated by convert_sprite_bmps_to_rgb565.py",
        "SPRITES = {",
    ]

    for record in records:
        lines.append("    %r: {" % record["name"])
        lines.append("        'file': %r," % record["file"])
        lines.append("        'width': %d," % record["width"])
        lines.append("        'height': %d," % record["height"])
        lines.append("        'transparent_key': %r," % (transparent_key,))
        lines.append("    },")

    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="ascii")


def convert_directory(source_dir, output_dir, gamma, transparent_key, manifest_name):
    if not source_dir.is_dir():
        raise FileNotFoundError("source directory not found: %s" % source_dir)

    output_dir.mkdir(parents=True, exist_ok=True)
    color_lut = build_color_lut(gamma)

    bmp_paths = sorted(
        path for path in source_dir.iterdir() if path.is_file() and path.suffix.lower() == ".bmp"
    )
    if not bmp_paths:
        print("No BMP files found in", source_dir)
        return 0, None

    records = []
    for bmp_path in bmp_paths:
        width, height, rgb565 = decode_bmp_to_rgb565(bmp_path, color_lut=color_lut)
        output_path = output_dir / (bmp_path.stem + ".rgb565")
        output_path.write_bytes(rgb565)

        records.append(
            {
                "name": bmp_path.stem,
                "file": output_path.name,
                "width": width,
                "height": height,
            }
        )

        message = "%s -> %s (%dx%d, %d bytes)" % (
            bmp_path.name,
            output_path.name,
            width,
            height,
            len(rgb565),
        )
        if transparent_key is not None:
            message += " [key %s]" % (transparent_key,)
        print(message)

    manifest_path = output_dir / manifest_name
    write_manifest(manifest_path, records, transparent_key)
    return len(records), manifest_path


def main():
    parser = argparse.ArgumentParser(
        description="Convert a folder of BMP sprites into raw RGB565 sprite files plus a manifest."
    )
    parser.add_argument(
        "source_dir",
        nargs="?",
        default=str(DEFAULT_SOURCE_DIR),
        help="directory containing .bmp sprite files (default: %(default)s)",
    )
    parser.add_argument(
        "output_dir",
        nargs="?",
        default=str(DEFAULT_OUTPUT_DIR),
        help="directory to write .rgb565 sprite files (default: %(default)s)",
    )
    parser.add_argument(
        "--gamma",
        type=float,
        default=DEFAULT_GAMMA,
        help="gamma correction to apply while converting (default: %(default)s)",
    )
    parser.add_argument(
        "--transparent-key",
        default=None,
        help="optional transparency color stored in the manifest as r,g,b, for example 255,0,255",
    )
    parser.add_argument(
        "--manifest-name",
        default=DEFAULT_MANIFEST_NAME,
        help="manifest filename to write in the output directory (default: %(default)s)",
    )
    args = parser.parse_args()

    source_dir = Path(args.source_dir)
    output_dir = Path(args.output_dir)
    transparent_key = parse_rgb_triplet(args.transparent_key)
    converted, manifest_path = convert_directory(
        source_dir,
        output_dir,
        gamma=args.gamma,
        transparent_key=transparent_key,
        manifest_name=args.manifest_name,
    )
    print("Converted", converted, "sprite BMP file(s).")
    if manifest_path is not None:
        print("Manifest:", manifest_path)


if __name__ == "__main__":
    main()